# Common configuration
database:
  host: "localhost"
  port: 5454
  username: "postgres"
  password: "password"
  database_name: "cryptos"
coin_market:
  # Live production environment with the latest market data.
  # See comments in development settings.
  base_url: "https://pro-api.coinmarketcap.com"
  # Specify your API key.
  api_key: "<secret-token>"
