# Common configuration
database:
  host: "localhost"
  port: 5454
  username: "postgres"
  password: "password"
  database_name: "cryptos"
coin_market:
  base_url: "https://pro-api.coinmarketcap.com"
  api_key: "secret-token"
