# Common configuration
application:
  host: 0.0.0.0
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "crypto_listings_latest"
coin_market:
  base_url: "https://pro-api.coinmarketcap.com"
  api_key: "secret-token"
