[package]
name = "coin-market-cap"
authors = ["Denis Deniz González <denis2.glez@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
serde_json = "1.0.68"

reqwest = { version = "0.11.5", default-features = false, features = [
    "json",
    "rustls-tls",
] }

[dev-dependencies]
